name: "Flake Check"
on:
  pull_request:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            accept-flake-config = true

      - name: Setup Nix Cache
        uses: nix-community/cache-nix-action@v7
        with:
          primary-key: nix-cache-${{ runner.os }}-${{ hashFiles('flake.lock', 'flake.nix') }}
          restore_prefixes_first_match: nix-cache-${{ runner.os }}-
          gc-max-store-size-linux: 1G

      - name: Check flake
        run: nix flake check

      - name: Build editor
        run: nix build .#default
